---
title: "Capital_Idea"
author: "Ethan Tenison"
date: "6/7/2020"
output: html_document
---

```{r libraries, message=FALSE}
#load libraries
library(haven)
library(dplyr)
library(janitor)
library(stringr)
library(readr)
library(ggplot2)
library(tidyr)
library(readxl)
library(anytime)
library(lubridate)
library(stringr)
library(broom)
library(janitor)


```




```{r read}

surveys_casenotes <- read_excel("data/Semester Surveys with Case Notes.xlsx")
surveys_casenotes$`Case_Notes.Record ID` <- as.numeric(surveys_casenotes$`Case_Notes.Record ID`)

meetinglength <- surveys_casenotes$`Session Minutes`

#Adding demogrpahic information
demographics <- read_excel("data/demographics.xlsx", 
    col_types = c("numeric", "skip", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "skip", "skip", "skip", "text", "numeric", 
        "skip", "text", "numeric", "numeric", 
        "text", "text", "text"))

surveys_casenotes <- left_join(surveys_casenotes, demographics, by = c("Case_Notes.Record ID" = "Record ID"))


```

## Data Cleaning 

The data set contains tons of duplicated information. Most students complete the information survey once a semester, although that is not always the case. However, each time a navigator interacts with the student, they input the survey information in again. 
```{r clean}


#Data cleaning demographic data
for (i in 1:length(demographics$Race)){
                  if(demographics$Race[i] == "Black or African American AND White" |
                     demographics$Race[i] == "American Indian or Alaska Native, Black or African American" |
                     demographics$Race[i] == "White, Other" | 
                     demographics$Race[i] == "White|Biracial" |
                     demographics$Race[i] == "White|N/A" |
                     demographics$Race[i] == "Other|hispanic" |
                     demographics$Race[i] == "Black or African American, Other" |
                     demographics$Race[i] == "White|Latino" |
                     demographics$Race[i] == "American Indian or Alaska Native, White" |
                     demographics$Race[i] == "American Indian or Alaska Native|Asian|Native Hawaiian or Pacific Islander|White" |
                     demographics$Race[i] == "American Indian or Alaska Native|White|pakistani" |
                     demographics$Race[i] == "American Indian or Alaska Native|White" |
                     demographics$Race[i] == "Black or African American|White" |
                     demographics$Race[i] == "hispanic" |
                     demographics$Race[i] == "Mexican" |
                     demographics$Race[i] == "hispanic" |
                     demographics$Race[i] == "American Indian or Alaska Native|Asian|Black or African American" |
                     demographics$Race[i] == "White|Afghan" |
                     demographics$Race[i] == "Mexican American" |
                     demographics$Race[i] == "Asian|White" |
                     demographics$Race[i] == "honduran" |
                     demographics$Race[i] == "White|Adopted" |
                     demographics$Race[i] == "Black or African American|White|Mexican" |
                     demographics$Race[i] == "American Indian or Alaska Native|Black or African American" |
                     demographics$Race[i] == "Hispanic/Latino"  )        {
                    demographics$Race[i] <- "Multiracial"
                  }
                   else if(demographics$Race[i] == "Somali" |
                           demographics$Race[i] == "Ethiopian"){        
                    demographics$Race[i] <- "Black or African American"
                 }
                else if(demographics$Race[i] == "Other|unknown"){        
                    demographics$Race[i] <- "Other"
                 }
}



#Joining casenotes and demographic data
surveys_casenotes <- left_join(surveys_casenotes, demographics, by = c("Case_Notes.Record ID" = "Record ID"))

#Converting dates to date formate
surveys_casenotes$`Survey Date` <- anytime::anydate(surveys_casenotes$`Survey Date`)

#Creating a variable for semester
surveys_casenotes$semester <- ""

for (i in 1:length(surveys_casenotes$`Survey Date`)){
  
  if(surveys_casenotes$`Survey Date`[i] < as.Date("2020-01-01")){        
                    surveys_casenotes$semester[i] <- "Fall 2019"
  }
  else if(surveys_casenotes$`Survey Date`[i] >= as.Date("2020-01-01") & surveys_casenotes$`Survey Date`[i] <= as.Date("2020-06-01") ){
                    surveys_casenotes$semester[i] <- "Spring 2020"
  }
  
}


#Add up total minutes for each student each semester 
surveys_casenotes$`Session Minutes` <- str_replace_all(surveys_casenotes$`Session Minutes`, " Minutes", "")
surveys_casenotes$`Session Minutes` <- as.numeric(surveys_casenotes$`Session Minutes`)

#Changing names to all upper 
surveys_casenotes$First <- toupper(surveys_casenotes$First)
surveys_casenotes$Last <- toupper(surveys_casenotes$Last)


#Getting rid of duplicate rows and sum all the minutes a navigator spent interacting with student per semester
survey <- surveys_casenotes %>% group_by_at(setdiff(names(surveys_casenotes), c("Session Minutes","Case Note", "Note Code", "Note Date Entered","Type of Contact","Note Importance","Note Meeting Date","Semester_Survey.Record ID", "Case_Notes.Record ID"))) %>% summarize(total_session_minutes = sum(`Session Minutes`))

#Removing entries were students took the entire survey multiple times per semester
surveyfall <- filter(survey, semester == "Fall 2019")
surveyfall <- surveyfall[(!duplicated(surveyfall$First) & !duplicated(surveyfall$Last) ), ]

surveyspring <- filter(survey, semester == "Spring 2020")
surveyspring <- surveyspring[(!duplicated(surveyspring$First) & !duplicated(surveyspring$Last) ), ]

surveys_casenotes <- bind_rows(surveyfall, surveyspring)
 



```



```{r plots}

#GGPLOTS

for(i in 1:ncol(surveys_casenotes)){
  

print(
  ggplot(surveys_casenotes, aes(x=surveys_casenotes[[i]])) +
  geom_histogram(stat = "count", fill = "lightblue") +
  xlab(colnames(surveys_casenotes)[i])
  )
  
  
}

```

# Demographic data

```{r demographics}

library(readxl)
demographics <- read_excel("data/demographics.xlsx")



```

```{r mult_reg}

#Creating a binary variable for whether a student is in good standing or not. 
for (i in 1:length(surveys_casenotes$`7 What is your current academic standing at ACC?`)) {
    if (surveys_casenotes$`7 What is your current academic standing at ACC?`[i] == "Good standing -") {
        surveys_casenotes$good_standing[i] <- 1
    }
    else {
      surveys_casenotes$good_standing[i] <- 0
    }
}

#removing nas from selected columns
mult_reg <- surveys_casenotes %>% ungroup() %>% dplyr::select(-c(`6a Are you enrolled in College Prep?`,`6b Are you awaiting acceptance into a`,
                                                                 `11d Please specify your OTHER financial`,`23a If yes, please explain`,
                                                                 `Is this an Intake Applicant or a current`, `Survey Date`, `First`,
                                                                 `Last`,`semester`, `26 What are your top two academic goals`,
                                                                 `27 What are your top two personal goals`,
                                                                 `28 What are your top two motivators for`,
                                                                 `29 How can your Career Navigator better`,
                                                                 `Estimated Graduation Date`,
                                                                 `1c Who is your assigned Career Navigator?`,
                                                                 "Academic Priority Level", "Financial Priority Level",
                                                                 "Situational Priority Level", "7 What is your current academic standing at ACC?",
                                                                 `16 Which best describes your current living situation?`,
                                                                 `Career Goal`, "Component"
                                                                 ))



mult_reg <- na.omit(mult_reg)

# cols <- c("good_standing","Academic  total score","Financial burden total score", "Situational total score",
#           "total_session_minutes","24 What form of transportation do you most commonly use?" )
# mult_reg <- surveys_casenotes[!rowSums(is.na(surveys_casenotes[cols])), ]


#Running the model

model <- glm(good_standing ~ .,
             family=binomial(link='logit'),data=mult_reg,  maxit = 100)

summary(model)
df <- as.data.frame(tidy(model))

mult_reg <- clean_names(mult_reg)

model2 <- glm(good_standing ~ academic_total_score +financial_burden_total_score + situational_total_score +,family=binomial(link='logit'),data=mult_reg)

df <- as.data.frame(tidy(model2))

```